#! /bin/bash

if [ -e "Base" ]
then
cd "Base"
qmake "CONFIG+=release"
make
qmake "CONFIG+=release" BaseStatic.pro
make
qmake "CONFIG+=release"
cd ..
fi

if [ -e "Hall" ]
then
cd "Hall"
qmake "CONFIG+=release"
make
make install
cd build
chmod +rx house.png install wav
cd ..
cd ..
fi

if [ -e "UpdateHall" ]
then
cd "UpdateHall"
qmake "CONFIG+=release"
make
cd ..
fi

if [ -e "Blackjack" ]
then
cd "Blackjack"
qmake "CONFIG+=release"
make
cd ..
fi

if [ -e "Chaodip" ]
then
cd "Chaodip"
qmake "CONFIG+=release"
make
cd ..
fi

if [ -e "ChineseChess" ]
then
cd "ChineseChess"
qmake "CONFIG+=release"
make
cd ..
fi

if [ -e "Chudd" ]
then
cd "Chudd"
qmake "CONFIG+=release"
make
cd ..
fi

if [ -e "GBMahjong" ]
then
cd "GBMahjong"
qmake "CONFIG+=release"
make
cd ..
fi

if [ -e "GDMahjong" ]
then
cd "GDMahjong"
qmake "CONFIG+=release"
make
cd ..
fi

if [ -e "GongZhu" ]
then
cd "GongZhu"
qmake "CONFIG+=release"
make
cd ..
fi

if [ -e "Interlink" ]
then
cd "Interlink"
qmake "CONFIG+=release"
make
cd ..
fi

if [ -e "LandBattle" ]
then
cd "LandBattle"
qmake "CONFIG+=release"
make
cd ..
fi

if [ -e "LandLord" ]
then
cd "LandLord"
qmake "CONFIG+=release"
make
cd ..
fi

if [ -e "NiuNiu" ]
then
cd "NiuNiu"
qmake "CONFIG+=release"
make
cd ..
fi

if [ -e "Renju" ]
then
cd "Renju"
qmake "CONFIG+=release"
make
cd ..
fi

if [ -e "Shisensho" ]
then
cd "Shisensho"
qmake "CONFIG+=release"
make
cd ..
fi

if [ -e "Suoha" ]
then
cd "Suoha"
qmake "CONFIG+=release"
make
cd ..
fi

if [ -e "Upgrade" ]
then
cd "Upgrade"
qmake "CONFIG+=release"
make
cd ..
fi

if [ -e "Hall/build" ]
then
cd "Hall/build"
rm -f *.a *.prl libBase.so libBase.so.1 libBase.so.1.0
mv libBase.so.1.0.0 libBase.so.1
fi



